// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// completeSearch_stability
CharacterVector completeSearch_stability(CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector compLeafSetR, double alphaR, double qR, double tauR);
RcppExport SEXP _ptwig_completeSearch_stability(SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP, SEXP qRSEXP, SEXP tauRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type tauR(tauRSEXP);
    rcpp_result_gen = Rcpp::wrap(completeSearch_stability(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR));
    return rcpp_result_gen;
END_RCPP
}
// completeSearch_basic_bifurcation
CharacterVector completeSearch_basic_bifurcation(CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector compLeafSetR, int MtR, int rbR, double qR);
RcppExport SEXP _ptwig_completeSearch_basic_bifurcation(SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP compLeafSetRSEXP, SEXP MtRSEXP, SEXP rbRSEXP, SEXP qRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< int >::type MtR(MtRSEXP);
    Rcpp::traits::input_parameter< int >::type rbR(rbRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    rcpp_result_gen = Rcpp::wrap(completeSearch_basic_bifurcation(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, MtR, rbR, qR));
    return rcpp_result_gen;
END_RCPP
}
// completeSearch_basic_score
CharacterVector completeSearch_basic_score(CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector compLeafSetR, double qR, int top_widthR, int bottom_widthR, std::string orientationR);
RcppExport SEXP _ptwig_completeSearch_basic_score(SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP compLeafSetRSEXP, SEXP qRSEXP, SEXP top_widthRSEXP, SEXP bottom_widthRSEXP, SEXP orientationRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< int >::type top_widthR(top_widthRSEXP);
    Rcpp::traits::input_parameter< int >::type bottom_widthR(bottom_widthRSEXP);
    Rcpp::traits::input_parameter< std::string >::type orientationR(orientationRSEXP);
    rcpp_result_gen = Rcpp::wrap(completeSearch_basic_score(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, top_widthR, bottom_widthR, orientationR));
    return rcpp_result_gen;
END_RCPP
}
// SPAnalysisRS
Rcpp::List SPAnalysisRS(CharacterVector treeStar, CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector bigTreeSampleR, IntegerVector nBSampleR, CharacterVector compLeafSetR, double alphaR, double qR, double tauR, double deltaR);
RcppExport SEXP _ptwig_SPAnalysisRS(SEXP treeStarSEXP, SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP bigTreeSampleRSEXP, SEXP nBSampleRSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP, SEXP qRSEXP, SEXP tauRSEXP, SEXP deltaRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeStar(treeStarSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bigTreeSampleR(bigTreeSampleRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nBSampleR(nBSampleRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type tauR(tauRSEXP);
    Rcpp::traits::input_parameter< double >::type deltaR(deltaRSEXP);
    rcpp_result_gen = Rcpp::wrap(SPAnalysisRS(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, alphaR, qR, tauR, deltaR));
    return rcpp_result_gen;
END_RCPP
}
// SPAnalysisR2S
Rcpp::List SPAnalysisR2S(CharacterVector treeStar, CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector bigTreeSampleR, IntegerVector nBSampleR, CharacterVector compLeafSetR, int MtR, int rbR, double qR, double deltaR);
RcppExport SEXP _ptwig_SPAnalysisR2S(SEXP treeStarSEXP, SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP bigTreeSampleRSEXP, SEXP nBSampleRSEXP, SEXP compLeafSetRSEXP, SEXP MtRSEXP, SEXP rbRSEXP, SEXP qRSEXP, SEXP deltaRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeStar(treeStarSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bigTreeSampleR(bigTreeSampleRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nBSampleR(nBSampleRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< int >::type MtR(MtRSEXP);
    Rcpp::traits::input_parameter< int >::type rbR(rbRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type deltaR(deltaRSEXP);
    rcpp_result_gen = Rcpp::wrap(SPAnalysisR2S(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, MtR, rbR, qR, deltaR));
    return rcpp_result_gen;
END_RCPP
}
// simpleSPAnalysis
Rcpp::List simpleSPAnalysis(CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector compLeafSetR, int MtR, int rbR, double qR, double q0R, int top_width1, int bottom_width1, int top_width2, int bottom_width2);
RcppExport SEXP _ptwig_simpleSPAnalysis(SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP compLeafSetRSEXP, SEXP MtRSEXP, SEXP rbRSEXP, SEXP qRSEXP, SEXP q0RSEXP, SEXP top_width1SEXP, SEXP bottom_width1SEXP, SEXP top_width2SEXP, SEXP bottom_width2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< int >::type MtR(MtRSEXP);
    Rcpp::traits::input_parameter< int >::type rbR(rbRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type q0R(q0RSEXP);
    Rcpp::traits::input_parameter< int >::type top_width1(top_width1SEXP);
    Rcpp::traits::input_parameter< int >::type bottom_width1(bottom_width1SEXP);
    Rcpp::traits::input_parameter< int >::type top_width2(top_width2SEXP);
    Rcpp::traits::input_parameter< int >::type bottom_width2(bottom_width2SEXP);
    rcpp_result_gen = Rcpp::wrap(simpleSPAnalysis(treeSample1R, nSample1R, compLeafSetR, MtR, rbR, qR, q0R, top_width1, bottom_width1, top_width2, bottom_width2));
    return rcpp_result_gen;
END_RCPP
}
// VerifyingRho
bool VerifyingRho(CharacterVector treeR, CharacterVector compLeafSetR);
RcppExport SEXP _ptwig_VerifyingRho(SEXP treeRSEXP, SEXP compLeafSetRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR(treeRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    rcpp_result_gen = Rcpp::wrap(VerifyingRho(treeR, compLeafSetR));
    return rcpp_result_gen;
END_RCPP
}
// computeFD
int computeFD(CharacterVector treeR1, CharacterVector treeR2);
RcppExport SEXP _ptwig_computeFD(SEXP treeR1SEXP, SEXP treeR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR1(treeR1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeR2(treeR2SEXP);
    rcpp_result_gen = Rcpp::wrap(computeFD(treeR1, treeR2));
    return rcpp_result_gen;
END_RCPP
}
// computeFDP
float computeFDP(CharacterVector treeR1, CharacterVector treeR2);
RcppExport SEXP _ptwig_computeFDP(SEXP treeR1SEXP, SEXP treeR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR1(treeR1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeR2(treeR2SEXP);
    rcpp_result_gen = Rcpp::wrap(computeFDP(treeR1, treeR2));
    return rcpp_result_gen;
END_RCPP
}
// computeRank
int computeRank(CharacterVector treeR);
RcppExport SEXP _ptwig_computeRank(SEXP treeRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR(treeRSEXP);
    rcpp_result_gen = Rcpp::wrap(computeRank(treeR));
    return rcpp_result_gen;
END_RCPP
}
// computeSimilarity
int computeSimilarity(CharacterVector treeR1, CharacterVector treeR2);
RcppExport SEXP _ptwig_computeSimilarity(SEXP treeR1SEXP, SEXP treeR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR1(treeR1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeR2(treeR2SEXP);
    rcpp_result_gen = Rcpp::wrap(computeSimilarity(treeR1, treeR2));
    return rcpp_result_gen;
END_RCPP
}
// computeNewSubposet
Rcpp::List computeNewSubposet(CharacterVector treeSampleR, IntegerVector nSampleR, CharacterVector compLeafSetR, int MtR, int rbR);
RcppExport SEXP _ptwig_computeNewSubposet(SEXP treeSampleRSEXP, SEXP nSampleRSEXP, SEXP compLeafSetRSEXP, SEXP MtRSEXP, SEXP rbRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSampleR(treeSampleRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSampleR(nSampleRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< int >::type MtR(MtRSEXP);
    Rcpp::traits::input_parameter< int >::type rbR(rbRSEXP);
    rcpp_result_gen = Rcpp::wrap(computeNewSubposet(treeSampleR, nSampleR, compLeafSetR, MtR, rbR));
    return rcpp_result_gen;
END_RCPP
}
// nullCoveringProbComputationS
float nullCoveringProbComputationS(CharacterVector treeStar, CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector compLeafSetR, double alphaR, double qR, double tauR, int B2);
RcppExport SEXP _ptwig_nullCoveringProbComputationS(SEXP treeStarSEXP, SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP, SEXP qRSEXP, SEXP tauRSEXP, SEXP B2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeStar(treeStarSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type tauR(tauRSEXP);
    Rcpp::traits::input_parameter< int >::type B2(B2SEXP);
    rcpp_result_gen = Rcpp::wrap(nullCoveringProbComputationS(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR, B2));
    return rcpp_result_gen;
END_RCPP
}
// computeStabilityRcppS
DataFrame computeStabilityRcppS(CharacterVector treeR, CharacterVector treeSampleR, IntegerVector nSampleR);
RcppExport SEXP _ptwig_computeStabilityRcppS(SEXP treeRSEXP, SEXP treeSampleRSEXP, SEXP nSampleRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR(treeRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSampleR(treeSampleRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSampleR(nSampleRSEXP);
    rcpp_result_gen = Rcpp::wrap(computeStabilityRcppS(treeR, treeSampleR, nSampleR));
    return rcpp_result_gen;
END_RCPP
}
// stableSearchRcppS
CharacterVector stableSearchRcppS(CharacterVector treeSampleR, IntegerVector nSampleR, CharacterVector compLeafSetR, double alphaR);
RcppExport SEXP _ptwig_stableSearchRcppS(SEXP treeSampleRSEXP, SEXP nSampleRSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSampleR(treeSampleRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSampleR(nSampleRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    rcpp_result_gen = Rcpp::wrap(stableSearchRcppS(treeSampleR, nSampleR, compLeafSetR, alphaR));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ptwig_completeSearch_stability", (DL_FUNC) &_ptwig_completeSearch_stability, 8},
    {"_ptwig_completeSearch_basic_bifurcation", (DL_FUNC) &_ptwig_completeSearch_basic_bifurcation, 8},
    {"_ptwig_completeSearch_basic_score", (DL_FUNC) &_ptwig_completeSearch_basic_score, 9},
    {"_ptwig_SPAnalysisRS", (DL_FUNC) &_ptwig_SPAnalysisRS, 12},
    {"_ptwig_SPAnalysisR2S", (DL_FUNC) &_ptwig_SPAnalysisR2S, 12},
    {"_ptwig_simpleSPAnalysis", (DL_FUNC) &_ptwig_simpleSPAnalysis, 11},
    {"_ptwig_VerifyingRho", (DL_FUNC) &_ptwig_VerifyingRho, 2},
    {"_ptwig_computeFD", (DL_FUNC) &_ptwig_computeFD, 2},
    {"_ptwig_computeFDP", (DL_FUNC) &_ptwig_computeFDP, 2},
    {"_ptwig_computeRank", (DL_FUNC) &_ptwig_computeRank, 1},
    {"_ptwig_computeSimilarity", (DL_FUNC) &_ptwig_computeSimilarity, 2},
    {"_ptwig_computeNewSubposet", (DL_FUNC) &_ptwig_computeNewSubposet, 5},
    {"_ptwig_nullCoveringProbComputationS", (DL_FUNC) &_ptwig_nullCoveringProbComputationS, 10},
    {"_ptwig_computeStabilityRcppS", (DL_FUNC) &_ptwig_computeStabilityRcppS, 3},
    {"_ptwig_stableSearchRcppS", (DL_FUNC) &_ptwig_stableSearchRcppS, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ptwig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
