// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// completeSearchRcpp
CharacterVector completeSearchRcpp(CharacterVector treeSample1R, CharacterVector treeSample2R, CharacterVector compLeafSetR, double alphaR, double qR, double tauR);
RcppExport SEXP _ptwig_completeSearchRcpp(SEXP treeSample1RSEXP, SEXP treeSample2RSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP, SEXP qRSEXP, SEXP tauRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type tauR(tauRSEXP);
    rcpp_result_gen = Rcpp::wrap(completeSearchRcpp(treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR));
    return rcpp_result_gen;
END_RCPP
}
// completeSearchRcppS
CharacterVector completeSearchRcppS(CharacterVector treeSample1R, IntegerVector nSample1R, CharacterVector treeSample2R, IntegerVector nSample2R, CharacterVector compLeafSetR, double alphaR, double qR, double tauR);
RcppExport SEXP _ptwig_completeSearchRcppS(SEXP treeSample1RSEXP, SEXP nSample1RSEXP, SEXP treeSample2RSEXP, SEXP nSample2RSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP, SEXP qRSEXP, SEXP tauRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample1R(treeSample1RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample1R(nSample1RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeSample2R(treeSample2RSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSample2R(nSample2RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    Rcpp::traits::input_parameter< double >::type qR(qRSEXP);
    Rcpp::traits::input_parameter< double >::type tauR(tauRSEXP);
    rcpp_result_gen = Rcpp::wrap(completeSearchRcppS(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR));
    return rcpp_result_gen;
END_RCPP
}
// computeFD
int computeFD(CharacterVector treeR1, CharacterVector treeR2);
RcppExport SEXP _ptwig_computeFD(SEXP treeR1SEXP, SEXP treeR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR1(treeR1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeR2(treeR2SEXP);
    rcpp_result_gen = Rcpp::wrap(computeFD(treeR1, treeR2));
    return rcpp_result_gen;
END_RCPP
}
// computeFDP
float computeFDP(CharacterVector treeR1, CharacterVector treeR2);
RcppExport SEXP _ptwig_computeFDP(SEXP treeR1SEXP, SEXP treeR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR1(treeR1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeR2(treeR2SEXP);
    rcpp_result_gen = Rcpp::wrap(computeFDP(treeR1, treeR2));
    return rcpp_result_gen;
END_RCPP
}
// computeRank
int computeRank(CharacterVector treeR);
RcppExport SEXP _ptwig_computeRank(SEXP treeRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR(treeRSEXP);
    rcpp_result_gen = Rcpp::wrap(computeRank(treeR));
    return rcpp_result_gen;
END_RCPP
}
// computeSimilarity
int computeSimilarity(CharacterVector treeR1, CharacterVector treeR2);
RcppExport SEXP _ptwig_computeSimilarity(SEXP treeR1SEXP, SEXP treeR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeR1(treeR1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type treeR2(treeR2SEXP);
    rcpp_result_gen = Rcpp::wrap(computeSimilarity(treeR1, treeR2));
    return rcpp_result_gen;
END_RCPP
}
// stableSearchRcpp
CharacterVector stableSearchRcpp(CharacterVector treeSampleR, CharacterVector compLeafSetR, double alphaR);
RcppExport SEXP _ptwig_stableSearchRcpp(SEXP treeSampleRSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSampleR(treeSampleRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    rcpp_result_gen = Rcpp::wrap(stableSearchRcpp(treeSampleR, compLeafSetR, alphaR));
    return rcpp_result_gen;
END_RCPP
}
// stableSearchRcppS
CharacterVector stableSearchRcppS(CharacterVector treeSampleR, IntegerVector nSampleR, CharacterVector compLeafSetR, double alphaR);
RcppExport SEXP _ptwig_stableSearchRcppS(SEXP treeSampleRSEXP, SEXP nSampleRSEXP, SEXP compLeafSetRSEXP, SEXP alphaRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type treeSampleR(treeSampleRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nSampleR(nSampleRSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type compLeafSetR(compLeafSetRSEXP);
    Rcpp::traits::input_parameter< double >::type alphaR(alphaRSEXP);
    rcpp_result_gen = Rcpp::wrap(stableSearchRcppS(treeSampleR, nSampleR, compLeafSetR, alphaR));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ptwig_completeSearchRcpp", (DL_FUNC) &_ptwig_completeSearchRcpp, 6},
    {"_ptwig_completeSearchRcppS", (DL_FUNC) &_ptwig_completeSearchRcppS, 8},
    {"_ptwig_computeFD", (DL_FUNC) &_ptwig_computeFD, 2},
    {"_ptwig_computeFDP", (DL_FUNC) &_ptwig_computeFDP, 2},
    {"_ptwig_computeRank", (DL_FUNC) &_ptwig_computeRank, 1},
    {"_ptwig_computeSimilarity", (DL_FUNC) &_ptwig_computeSimilarity, 2},
    {"_ptwig_stableSearchRcpp", (DL_FUNC) &_ptwig_stableSearchRcpp, 3},
    {"_ptwig_stableSearchRcppS", (DL_FUNC) &_ptwig_stableSearchRcppS, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ptwig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
