# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

completeSearchRcpp <- function(treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR) {
    .Call(`_ptwig_completeSearchRcpp`, treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR)
}

completeSearchRcppS <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR) {
    .Call(`_ptwig_completeSearchRcppS`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR)
}

computeFD <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeFD`, treeR1, treeR2)
}

computeFDP <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeFDP`, treeR1, treeR2)
}

computeRank <- function(treeR) {
    .Call(`_ptwig_computeRank`, treeR)
}

computeSimilarity <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeSimilarity`, treeR1, treeR2)
}

stableSearchRcpp <- function(treeSampleR, compLeafSetR, alphaR) {
    .Call(`_ptwig_stableSearchRcpp`, treeSampleR, compLeafSetR, alphaR)
}

stableSearchRcppS <- function(treeSampleR, nSampleR, compLeafSetR, alphaR) {
    .Call(`_ptwig_stableSearchRcppS`, treeSampleR, nSampleR, compLeafSetR, alphaR)
}

