# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

completeSearchRcpp <- function(treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR) {
    .Call(`_ptwig_completeSearchRcpp`, treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR)
}

completeSearchRcpp_V2 <- function(treeSample1R, treeSample2R, compLeafSetR, MtR, rbR, qR) {
    .Call(`_ptwig_completeSearchRcpp_V2`, treeSample1R, treeSample2R, compLeafSetR, MtR, rbR, qR)
}

completeSearchRcppS <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR) {
    .Call(`_ptwig_completeSearchRcppS`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR)
}

completeSearchRcppS_V2 <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, MtR, rbR, qR) {
    .Call(`_ptwig_completeSearchRcppS_V2`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, MtR, rbR, qR)
}

completeSearchRcppS_V3 <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, qoR) {
    .Call(`_ptwig_completeSearchRcppS_V3`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, qoR)
}

completeSearchRcppS_V4 <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, top_widthR, bottom_widthR, orientationR) {
    .Call(`_ptwig_completeSearchRcppS_V4`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, top_widthR, bottom_widthR, orientationR)
}

SPAnalysisR <- function(treeStar, treeSample1R, treeSample2R, bigTreeSampleR, compLeafSetR, alphaR, qR, tauR, deltaR) {
    .Call(`_ptwig_SPAnalysisR`, treeStar, treeSample1R, treeSample2R, bigTreeSampleR, compLeafSetR, alphaR, qR, tauR, deltaR)
}

SPAnalysisR2 <- function(treeStar, treeSample1R, treeSample2R, bigTreeSampleR, compLeafSetR, MtR, rbR, qR, deltaR) {
    .Call(`_ptwig_SPAnalysisR2`, treeStar, treeSample1R, treeSample2R, bigTreeSampleR, compLeafSetR, MtR, rbR, qR, deltaR)
}

SPAnalysisRS <- function(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, alphaR, qR, tauR, deltaR) {
    .Call(`_ptwig_SPAnalysisRS`, treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, alphaR, qR, tauR, deltaR)
}

SPAnalysisR2S <- function(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, MtR, rbR, qR, deltaR) {
    .Call(`_ptwig_SPAnalysisR2S`, treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, MtR, rbR, qR, deltaR)
}

simpleSPAnalysis <- function(treeSample1R, nSample1R, compLeafSetR, MtR, rbR, qR, q0R, top_width1, bottom_width1, top_width2, bottom_width2) {
    .Call(`_ptwig_simpleSPAnalysis`, treeSample1R, nSample1R, compLeafSetR, MtR, rbR, qR, q0R, top_width1, bottom_width1, top_width2, bottom_width2)
}

VerifyingRho <- function(treeR, compLeafSetR) {
    .Call(`_ptwig_VerifyingRho`, treeR, compLeafSetR)
}

computeFD <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeFD`, treeR1, treeR2)
}

computeFDP <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeFDP`, treeR1, treeR2)
}

computeRank <- function(treeR) {
    .Call(`_ptwig_computeRank`, treeR)
}

computeSimilarity <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeSimilarity`, treeR1, treeR2)
}

computeNewSubposet <- function(treeSampleR, nSampleR, compLeafSetR, MtR, rbR) {
    .Call(`_ptwig_computeNewSubposet`, treeSampleR, nSampleR, compLeafSetR, MtR, rbR)
}

nullCoveringProbComputation <- function(treeStar, treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR, B2) {
    .Call(`_ptwig_nullCoveringProbComputation`, treeStar, treeSample1R, treeSample2R, compLeafSetR, alphaR, qR, tauR, B2)
}

nullCoveringProbComputationS <- function(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR, B2) {
    .Call(`_ptwig_nullCoveringProbComputationS`, treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR, B2)
}

stableSearchRcpp <- function(treeSampleR, compLeafSetR, alphaR) {
    .Call(`_ptwig_stableSearchRcpp`, treeSampleR, compLeafSetR, alphaR)
}

stableSearchRcppS <- function(treeSampleR, nSampleR, compLeafSetR, alphaR) {
    .Call(`_ptwig_stableSearchRcppS`, treeSampleR, nSampleR, compLeafSetR, alphaR)
}

