# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

completeSearch_stability <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR) {
    .Call(`_ptwig_completeSearch_stability`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR)
}

completeSearch_basic_bifurcation <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, MtR, rbR, qR) {
    .Call(`_ptwig_completeSearch_basic_bifurcation`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, MtR, rbR, qR)
}

completeSearch_basic_score <- function(treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, top_widthR, bottom_widthR, orientationR) {
    .Call(`_ptwig_completeSearch_basic_score`, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, qR, top_widthR, bottom_widthR, orientationR)
}

SPAnalysisRS <- function(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, alphaR, qR, tauR, deltaR) {
    .Call(`_ptwig_SPAnalysisRS`, treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, alphaR, qR, tauR, deltaR)
}

SPAnalysisR2S <- function(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, MtR, rbR, qR, deltaR) {
    .Call(`_ptwig_SPAnalysisR2S`, treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, bigTreeSampleR, nBSampleR, compLeafSetR, MtR, rbR, qR, deltaR)
}

simpleSPAnalysis <- function(treeSample1R, nSample1R, compLeafSetR, MtR, rbR, qR, q0R, top_width1, bottom_width1, top_width2, bottom_width2) {
    .Call(`_ptwig_simpleSPAnalysis`, treeSample1R, nSample1R, compLeafSetR, MtR, rbR, qR, q0R, top_width1, bottom_width1, top_width2, bottom_width2)
}

VerifyingRho <- function(treeR, compLeafSetR) {
    .Call(`_ptwig_VerifyingRho`, treeR, compLeafSetR)
}

computeFD <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeFD`, treeR1, treeR2)
}

computeFDP <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeFDP`, treeR1, treeR2)
}

computeRank <- function(treeR) {
    .Call(`_ptwig_computeRank`, treeR)
}

computeSimilarity <- function(treeR1, treeR2) {
    .Call(`_ptwig_computeSimilarity`, treeR1, treeR2)
}

computeNewSubposet <- function(treeSampleR, nSampleR, compLeafSetR, MtR, rbR) {
    .Call(`_ptwig_computeNewSubposet`, treeSampleR, nSampleR, compLeafSetR, MtR, rbR)
}

nullCoveringProbComputationS <- function(treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR, B2) {
    .Call(`_ptwig_nullCoveringProbComputationS`, treeStar, treeSample1R, nSample1R, treeSample2R, nSample2R, compLeafSetR, alphaR, qR, tauR, B2)
}

computeStabilityRcppS <- function(treeR, treeSampleR, nSampleR) {
    .Call(`_ptwig_computeStabilityRcppS`, treeR, treeSampleR, nSampleR)
}

stableSearchRcppS <- function(treeSampleR, nSampleR, compLeafSetR, alphaR) {
    .Call(`_ptwig_stableSearchRcppS`, treeSampleR, nSampleR, compLeafSetR, alphaR)
}

